<a href="https://colab.research.google.com/github/Lokhande10/Data-Analysis-with-Python/blob/main/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import sys

In [2]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b=np.array([1,.5,2,.9,10])
b

array([ 1. ,  0.5,  2. ,  0.9, 10. ])

In [ ]:
#Multi indexing

In [4]:
b[[0,2,-1]]

array([ 1.,  2., 10.])

In [ ]:
# Array Types

In [5]:
a.dtype

dtype('int64')

In [6]:
b.dtype

dtype('float64')

In [9]:
c=np.array(['a','b','c','d'])
c.dtype   
c                    #String is shown as unique 

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [11]:
d=np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
d.shape
#d.ndim
#d.size

(2, 3)

In [14]:
d.ndim

2

In [15]:
d.size

6

In [16]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [17]:
a+10                          # Vectorization

array([10, 11, 12, 13, 14])

In [18]:
a*10

array([ 0, 10, 20, 30, 40])

In [20]:
A=np.random.randint(100,size=(3,3))
A

array([[59, 57, 24],
       [63, 33,  4],
       [10, 92, 42]])

In [22]:
A>30

array([[ True,  True, False],
       [ True,  True, False],
       [False,  True,  True]])

In [24]:
A[A>30]

array([59, 57, 63, 33, 92, 42])

In [29]:
sys.getsizeof(1)

28

In [31]:
sys.getsizeof(10**100)  # size of objects in memory

72

In [32]:
np.int8

numpy.int8

In [33]:
l=list(range(1000))
a=np.arange(1000)



In [37]:
%time np.sum(a**2)

CPU times: user 162 µs, sys: 19 µs, total: 181 µs
Wall time: 187 µs


332833500