<a href="https://colab.research.google.com/github/Lokhande10/Data-Analysis-with-Python/blob/main/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b=np.array([1,.5,2,.9,10])
b

array([ 1. ,  0.5,  2. ,  0.9, 10. ])

In [ ]:
#Multi indexing

In [4]:
b[[0,2,-1]]

array([ 1.,  2., 10.])

In [ ]:
# Array Types

In [5]:
a.dtype

dtype('int64')

In [6]:
b.dtype

dtype('float64')

In [9]:
c=np.array(['a','b','c','d'])
c.dtype   
c                    #String is shown as unique 

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [11]:
d=np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
d.shape
#d.ndim
#d.size

(2, 3)

In [14]:
d.ndim

2

In [15]:
d.size

6