<a href="https://colab.research.google.com/github/Lokhande10/Data-Analysis-with-Python/blob/main/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import sys

In [2]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b=np.array([1,.5,2,.9,10])
b

array([ 1. ,  0.5,  2. ,  0.9, 10. ])

In [ ]:
#Multi indexing

In [4]:
b[[0,2,-1]]

array([ 1.,  2., 10.])

In [ ]:
# Array Types

In [5]:
a.dtype

dtype('int64')

In [6]:
b.dtype

dtype('float64')

In [9]:
c=np.array(['a','b','c','d'])
c.dtype   
c                    #String is shown as unique 

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [11]:
d=np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
d.shape
#d.ndim
#d.size

(2, 3)

In [14]:
d.ndim

2

In [15]:
d.size

6

In [16]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [17]:
a+10                          # Vectorization

array([10, 11, 12, 13, 14])

In [18]:
a*10

array([ 0, 10, 20, 30, 40])

In [20]:
A=np.random.randint(100,size=(3,3))
A

array([[59, 57, 24],
       [63, 33,  4],
       [10, 92, 42]])

In [22]:
A>30

array([[ True,  True, False],
       [ True,  True, False],
       [False,  True,  True]])

In [24]:
A[A>30]

array([59, 57, 63, 33, 92, 42])

In [29]:
sys.getsizeof(1)

28

In [31]:
sys.getsizeof(10**100)  # size of objects in memory

72

In [32]:
np.int8

numpy.int8

In [33]:
l=list(range(1000))
a=np.arange(1000)



In [37]:
%time np.sum(a**2)

CPU times: user 162 µs, sys: 19 µs, total: 181 µs
Wall time: 187 µs


332833500

In [45]:
import pandas as pd
from google.colab import files
uploaded=files.upload()

Saving survey-csv.csv to survey-csv.csv


In [46]:
import io
df2 = pd.read_csv(io.BytesIO(uploaded['survey-csv.csv']))

In [74]:
df=pd.read_csv('survey-csv.csv')
df

Variable  ...        Footnotes
0      _01_Current and Capital Expenditure: Total R&D...  ...         8 and 20
1      _01_Current and Capital Expenditure: Total R&D...  ...         8 and 20
2      _01_Current and Capital Expenditure: Total R&D...  ...   8 and 9 and 20
3      _01_Current and Capital Expenditure: Total R&D...  ...         8 and 20
4      _01_Current and Capital Expenditure: Total R&D...  ...         8 and 20
...                                                  ...  ...              ...
14941  _89_Reason for not engaging more with CRIs or ...  ...        19 and 21
14942  _89_Reason for not engaging more with CRIs or ...  ...  9 and 19 and 21
14943  _89_Reason for not engaging more with CRIs or ...  ...               21
14944  _89_Reason for not engaging more with CRIs or ...  ...               21
14945  _89_Reason for not engaging more with CRIs or ...  ...         9 and 21

[14946 rows x 7 columns]

In [70]:
df.head()

Variable  ...       Footnotes
0  _01_Current and Capital Expenditure: Total R&D...  ...        8 and 20
1  _01_Current and Capital Expenditure: Total R&D...  ...        8 and 20
2  _01_Current and Capital Expenditure: Total R&D...  ...  8 and 9 and 20
3  _01_Current and Capital Expenditure: Total R&D...  ...        8 and 20
4  _01_Current and Capital Expenditure: Total R&D...  ...        8 and 20

[5 rows x 7 columns]

In [75]:
df.shape

(14946, 7)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14946 entries, 0 to 14945
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Variable            14946 non-null  object
 1   Breakdown           14946 non-null  object
 2   Breakdown_category  14946 non-null  object
 3   Year                14946 non-null  int64 
 4   RD_Value            14946 non-null  object
 5   Units               14946 non-null  object
 6   Footnotes           14946 non-null  object
dtypes: int64(1), object(6)
memory usage: 817.5+ KB


In [51]:
df.dtypes

Variable              object
Breakdown             object
Breakdown_category    object
Year                   int64
RD_Value              object
Units                 object
Footnotes             object
dtype: object

In [54]:
import matplotlib.pyplot as plt


In [76]:
df2=df['RD_Value']
df2.head(10)

0     91
1     89
2     89
3      5
4      9
5      9
6    671
7    673
8    763
9      6
Name: RD_Value, dtype: object